### ISSUE TITLE
Attribute name "crossorigin" associated with an element type "link" must be followed by the ' = ' character.

### ISSUE THREAD

**Issue by 192933488S** [Vitaliy-1/JATS2LaTeX#5]
Testing the swift tool on Win 10 with sample xml, but getting this error:

```
PS C:\dev\test\dois\requirements> java -jar .\latex.jar article_english.xml article_english.tex article_english.bib
[Fatal Error] article_english.xml:15:76: Attribute name "crossorigin" associated with an element type "link" must be followed by the ' = ' character.
Exception in thread "main" org.xml.sax.SAXParseException; systemId: file:///C:/dev/test/dois/requirements/article_english.xml; lineNumber: 15; columnNumber: 76; Attribute name "crossorigin" associated with an element type "link" must be followed by the ' = ' character.
        at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:261)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
        at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:178)
        at org.emed.main.Main.writerToFile(Main.java:115)
        at org.emed.main.Main.main(Main.java:56)
PS C:\dev\test\dois\requirements>
```

```
PS C:\dev\test\dois\requirements> java --version
openjdk 16.0.1 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)
PS C:\dev\test\dois\requirements>
```

**Comment by utkarshsingh8** [comment]
replace crossorigin with **crossorigin=""**
